cloud_pct.innerHTML =reponse.cloud_pct
  temp.innerHTML =response.temp
  feels_lik.innerHTMLe= response.feels_like
  humidity.innerHTML = response.humidity
  min_temp.innerHTML =response.min_temp
  max_temp.innerHTML =response..max_temp
  wind_speed.innerHTML = response.wind_speed
  wind_degrees.innerHTML = response.wind_degrees
  sunrise.innerHTML =response.sunrise
  sunset.innerHTML = response.sunset